#!/usr/bin/python
"""
ShowMe  - Determine which Missouri QSO Party stations 
          qualify for the ShowMe and/or MISSOURI awards

Update History:
* Thu Dec 09 2019 Mike Heitmann, N0SO <n0so@arrl.net>
- V0.0.1 - Start of work
* Thu Dec 10 2019 Mike Heitmann, N0SO <n0so@arrl.net>
- V0.1.0 - Working command  line version of SHOWME and
- MISSOURI awards.
- Needs more testing and tweaking - Files with lots of
- bad QSO errors make the output confusing to read.
- Needs to factor in use of COMMONCALLS and WILDCARD.
- No GUI
"""

import os.path
import sys
import argparse
VERSION = '0.1.0'
ARGS = None

DEVMODPATH = ['moqputils', 'cabrilloutils']
# If the development module source paths exist, 
# add them to the python path
for mypath in DEVMODPATH:
    if ( os.path.exists(mypath) and \
                       (os.path.isfile(mypath) == False) ):
        sys.path.insert(0,mypath)
#print('Python path = %s'%(sys.path))
        
DESCRIPTION = \
"""showme  - Determine which Missouri QSO Party stations 
          qualify for the ShowMe and/or MISSOURI awards

                
          Based on 2019 MOQP Rules
"""

EPILOG = \
"""
Running with no parameters will launch the GUI.
"""

class get_args():
    def __init__(self):
        if __name__ == '__main__':
            self.args = self.getargs()
            
    def getargs(self):
        parser = argparse.ArgumentParser(\
                               description = DESCRIPTION,
                                           epilog = EPILOG)
        parser.add_argument('-v', '--version', action='version', version = VERSION)
        parser.add_argument("-i", "--inputpath", default=None,
            help="Specifies the path to the folder that contains the log files to summarize.")
        return parser.parse_args()


if __name__ == '__main__':
   args = get_args()
   
   if (args.args.inputpath):
       print(args.args.inputpath)
       from showmeaward import ShowMe
       app = ShowMe(args.args.inputpath)
   else:
       from showme_ui import ui
       app=ui()
        
