#!/usr/bin/env python
"""
Update History - See __init__.py 
"""

DESCRIPTION = \
"""makehtml.py  - Generates an html table of certificate winners with
                  links to downloadable certificate file  using the same 
                  excel sheet used to mailmerge the master combined
                  .PDF document.
          Parameters: 
            -c --call_list - A list of callsigns, operators and the 
                             file name desired to appear in the link.
                             This file should be generated by taking the
                             output from mqplabels and copy/pasting the
                             call, operator and filename columns from
                             the report to a new .csv file. The 
                             mqplabels file should also be used to
                             generate the certificate files  via a "mail
                             merge" process the ensure the certificate
                             file names align with the file list.
            -f --file_path - Path to file that holds all of the 
                             PDF certificates. 
                             files.
          The resulting html table is intended to be copy/pasted
          into a SHOWME or MISSOURI report for the web page.
"""

EPILOG = \
"""
Running with no parameters will launch the GUI (eventually).
"""

TABLESTARTS = \
"""
<table>
<tr><th>STATION</th><th>OPERATORS</th><th>AWARD DOWNLOAD LINK</th></tr>
"""

TABLEROWS = \
"""
<tr><td>{}</td><td>{}</td><td><a href="./downloads/{}">{} DOWNLOAD</a></td></tr> 
"""

TABLESTARTC = \
"""
<table>
<tr><th>AWARD</th><th>STATION</th><th>OPERATORS</th><th>AWARD DOWNLOAD LINK</th></tr>
"""

TABLEROWC = \
"""
<tr><td>{}</td><td>{}</td><td>{}</td><td><a href="./{}">{} DOWNLOAD</a></td></tr> 
"""
from pypdf import PdfReader, PdfWriter
from __init__ import VERSION
import os, sys, csv

ARGS = None

class get_args():
    def __init__(self):
        if __name__ == '__main__':
            self.args = self.getargs()
            
    def getargs(self):
        parser = argparse.ArgumentParser(\
                               description = DESCRIPTION,
                                           epilog = EPILOG)

        parser.add_argument('-v', '--version', 
                                  action='version', 
                                  version = VERSION)

        parser.add_argument('-c', '--call_list',
            default=None,
            help="""Path to the .csv file exported from the spreadsheet 
            used to create the merged pdf holding all of the 
            certificates.""")

        parser.add_argument('-f', '--file_path',
            default=None,
            help="""The path to the file containing all of the pdf
                    certificate files. These should be the files created
                    by the mail merge using the mqplables report output.""")

        args = parser.parse_args()
        #print(args)
        return args


class htmlCerts():

    def __init__(self):
        pass

    """
    Splits a PDF file into individual pages, saving each page as a new PDF.

    Args:
        input_pdf_path (str): The path to the input PDF file.
        output_fname (str): file name for output PDF file.
        page_list (list): List of page numbers (1 based) to extract.
        output_folder (str): The folder where the split pages will be saved.

    # Example usage:
    # Assuming 'your_document.pdf' is in the same directory as your script
    # split_pdf_into_pages("missouri-2025-merged.pdf")
    """
    def split_pdf_into_pages(self,
			    input_pdf_path,
                            output_fname, 
                            page_list=[1], 
                            output_folder="output_pages"):
        reader = PdfReader(input_pdf_path)
        num_pages = len(page_list)

        # Create the output folder if it doesn't exist
        # import os
        os.makedirs(output_folder, exist_ok=True)

        for i in page_list:
            writer = PdfWriter()
            writer.add_page(reader.pages[i-1])

            output_filename = os.path.join(output_folder, output_fname)
            with open(output_filename, "wb") as output_pdf:
                writer.write(output_pdf)


    def find_pages(self, pdf_file, search_term):
        reader = PdfReader(pdf_file)
        found_pages = []

        for page_num, page in enumerate(reader.pages):
            text = page.extract_text()
            if search_term.lower() in text.lower():
                found_pages.append(page_num + 1) # Page numbers are 1-indexed
        return found_pages

    def Appmain(self, call_list, file_path):
        print(TABLESTARTS)
        """
        Open the .csv file that contains list of callsigns
        """
        with open(call_list, mode='r', newline='') as fname:
            csv_reader = csv.DictReader(fname, delimiter='\t')
            for row in csv_reader:
                if (row['OPERATORS'] == None or
                        row['OPERATORS'].strip() == '' or
                        len(row['OPERATORS']) == 0 ):
                    #Single-op - look for station call in text
                    search_term = row['CALL']
                else:
                    """
                    Multi-op - look for op name in text 
                    search for op name.
                    """
                    search_term = row['NAME'].strip()
                #Extract the one file for this line.
                pages = self.find_pages( pdf_file=file_path, 
                            search_term=search_term)
                if pages:
                    #print(f"Extracting {row['FILE']}, page {pages} for {row['CALL']} op {search_term}") 
                    self.split_pdf_into_pages(   file_path, 
                                    row['FILE'],
                                    page_list=[pages[0]], 
                                    output_folder='downloads')
                    print(TABLEROWS.format(\
                          row['CALL'],
                          row['OPERATORS'],
                          row['FILE'],
                          row['FILE']))

        print('</table>') 



